runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: main2.application

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

libraries:
- name: MySQLdb
  version: "latest"
- name: pycrypto
  version: "latest"

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: gigichallange:europe-west1:gigichallange
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: gigilatrottola